spring:
  jpa:
    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      schema-locations: classpath*:schema.sql
#      data-locations: classpath*:data.sql

